# serverless.yml

service: thestarbucksapp

provider:
  name: aws
  runtime: nodejs20.x  # Ensure this matches a version supported by AWS Lambda
  region: ca-central-1
  environment:
    USER_TABLE: StarbucksApplicationUserTable

functions:
  createUser: 
    handler: lambda/functions/createUser.handler
    events:
      - http:
          path: users/create
          method: post
          cors: true
  authenticateUser:
    handler: lambda/functions/authenticateUser.handler
    events:
      - http:
          path: users/authenticate
          method: post
          cors: true

package:
  individually: true
  patterns:
    - '!**' # Exclude everything by default
    - 'lambda/**' # Include all files in the lambda directory

resources:
  Resources:
    StarbucksUserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: StarbucksApplicationUserTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
